version: '3.5'
services:
  db:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
#      - config.support_escapes=true



  elk:
    image: elasticsearch:7.17.15
    hostname: elastic
    container_name: elastic
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "10"
    environment:
      - discovery.type=single-node
      - node.name=odfe-node
      - discovery.seed_hosts=odfe-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
#    ports:
#      - "9200:9200"
#      - "9600:9600"


  app:
    hostname: app
    container_name: app
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "10"
    build:
      context: ./MusicPlayerDictionary
      dockerfile: Dockerfile
    depends_on:
      - "elk"
      - "db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app?prepareThreshold=0
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/app?prepareThreshold=0
      - SPRING_ELASTICSEARCH_URIS=elastic:9200
      - token=qwertyuiopasdfghjkljdfnjsafdjsflfhaasdjfhdskfkjafkjasfhlkfjzxcvbnm
      #      - выставил в true ,чтобы скрипты накатывались, можно потом подумать будет как их в образе накатить получше
    #      - SPRING_LIQUIBASE_ENABLED=true
    ports:
      - "8080:8080"
