version: '3.5'
services:
  #  db:
  #    image: postgres:12.16
  #    container_name: postgres
  #    ports:
  #      - "5433:5432"
  #    environment:
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_PASSWORD=postgres
  #      - POSTGRES_DB=demo
  #      - config.support_escapes=true
  #  hotels:
  #    build:
  #      context: ./
  #      dockerfile: Dockerfile
  #    depends_on:
  #      - "odfe-node"
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.31.233:5433/postgres
  #    ports:
  #      - "8080:8080"
  elk:
    image: elasticsearch:7.17.15
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "10"
    container_name: odfe-node
    environment:
      - discovery.type=single-node
      - node.name=odfe-node
      - discovery.seed_hosts=odfe-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - odfe-net
  app:
    build:
      context: ./MusicPlayerDictionary
      dockerfile: Dockerfile
    depends_on:
      - "elk"
    environment:
      #      - необходимо прописать ipconfig и вставить сюда ip локальной сети, потому что localhost в контейнере свой
      - SPRING_ELASTICSEARCH_URIS=172.51.0.2:9200
      #      - выставил в true ,чтобы скрипты накатывались, можно потом подумать будет как их в образе накатить получше
    #      - SPRING_LIQUIBASE_ENABLED=true
    ports:
      - "8080:8080"
    networks:
      - odfe-net
networks:
  odfe-net:
    ipam:
      config:
        - subnet: 172.51.0.0/24


volumes:
  odfe-data:
  db:
  logstash: